title: Streamdata Subscribe - Reddit
url: subscribe.streamdata.gallery
tag: Subscribe Reddit
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-subscribe
github_repo: subscribe-github
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
